parameters:
#    landing_pages_complacelas.example.class: Landing\Pages\ComplacelasBundle\Example

services:
#    landing_pages_complacelas.example:
#        class: %landing_pages_complacelas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
