landing_pages_todosganan_subscribe:
    resource: "@LandingPagesTodosgananSubscribeBundle/Resources/config/routing.yml"
    prefix:   /

landing_pages_todosganan_site_rewards:
    resource: "@LandingPagesTodosgananSiteRewardsBundle/Resources/config/routing.yml"
    prefix:   /

landing_pages_todosganan_site_home:
    resource: "@LandingPagesTodosgananSiteHomeBundle/Resources/config/routing.yml"
    prefix:   /

landing_pages_chatearenvivo_complacelas:
    resource: "@LandingPagesChatearenvivoComplacelasBundle/Resources/config/routing.yml"
    prefix:   /

landing_pages_todosganan_gadgets:
    resource: "@LandingPagesTodosgananGadgetsBundle/Resources/config/routing.yml"
    prefix:   /

landing_pages_core:
    resource: "@LandingPagesCoreBundle/Resources/config/routing.yml"
    prefix:   /

