parameters:
#    landing_pages_todosganan_site_rewards.example.class: Landing\Pages\Todosganan\Site\RewardsBundle\Example

services:
#    landing_pages_todosganan_site_rewards.example:
#        class: %landing_pages_todosganan_site_rewards.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
