parameters:
#    landing_pages_todosganan_site_home.example.class: Landing\Pages\Todosganan\Site\HomeBundle\Example

services:
#    landing_pages_todosganan_site_home.example:
#        class: %landing_pages_todosganan_site_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
